name: js_fit
description: JsFit - Tu entrenador personal inclusivo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - android-icon/icon.png
    - assets/icon.png
